export const translations = {
  en: {
    settings: "Settings",
    english: "English",
    russian: "Russian",
    language: "Language",
    temperature: "Temperature",
    windSpeed: "Wind speed",
    celsius: "Celsius",
    fahrenheit: "Fahrenheit",
    mph: "Miles per hour",
    kmh: "Kilometers per hour",
    // Weather UI translations
    today: "Today",
    loading: "Loading...",
    yourCity: "Your city...",
    observations: "Observations",
    observedAt: "Observed at",
    signIn: "Sign in",
    yourAccount: "Your account",
    home: "Home",
    news: "News",
    searchMEX: "Search MEX",
    weather: "Weather",
    enterCity: "Enter a city",
    myLocations: "My locations",
    recentSearches: "Recent searches",
    infoText1:
      "We use your postcode to give you relevant local info across the MEX.",
    infoText2:
      "Add more locations to keep up with what's happening in the places you care about.",
    infoText3: "You haven't searched for any locations yet.",
    infoText4: "Previous searches will appear here.",
    // Geolocation modal
    allowGeolocation: "Allow Geolocation?",
    needLocation: "We need your location to show weather data",
    decline: "Decline",
    accept: "Accept",
    agreeGeo: "Do your agree from geo?",
    // Weather descriptions and hourly forecast
    weatherDescription: "Weather: {description}",
    precipitation: "Precipitation",
    hourlyForecast: "Hourly Forecast",
    feelsLike: "Feels like",
    humidity: "Humidity",
    pressure: "Pressure",
    visibility: "Visibility",
    sunrise: "Sunrise",
    sunset: "Sunset",
    wind: "Wind",
    // Weather conditions
    clear: "Clear",
    clouds: "Cloudy",
    rain: "Rain",
    snow: "Snow",
    thunderstorm: "Thunderstorm",
    drizzle: "Drizzle",
    mist: "Mist",
    fog: "Fog",
    // Time periods
    morning: "Morning",
    afternoon: "Afternoon",
    evening: "Evening",
    night: "Night",
    // Days of week
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    sunday: "Sunday",
    // Footer translations
    exploreMex: "Explore the MEX",
    copyright:
      "Copyright © {year} MEX. The MEX is not responsible for the content of external sites.",
    readAboutApproach: "Read about our approach to external linking.",
    // About section
    aboutMexWeather: "About MEX Weather",
    faqs: "FAQs",
    feeds: "Feeds",
    elsewhere: "Elsewhere",
    openWeather: "OpenWeather",
    openOffice: "Open Office",
    // Collaborations
    mexWeatherAssociation: "Mex Weather in association with",
    // Observations
    observationStation: "Observation Station:",
    error404: "404!",
    // ads
    eminemAdDesc: "🔥 New album is out now!",
    aliAdDesc: "🏪 Store without problems",
    davinciAdDesc: "🎙️ Create your own videos now!",
    nestAdDesc: "🫦 Backend with cool framework",
    telegramAdDesc: "🚀 Messenger which works even in the parking",
  },
  ru: {
    settings: "Настройки",
    english: "Английский",
    russian: "Русский",
    language: "Язык",
    temperature: "Температура",
    windSpeed: "Скорость ветра",
    celsius: "Цельсий",
    fahrenheit: "Фаренгейт",
    mph: "Мили в час",
    kmh: "Км/ч",
    // Weather UI translations
    today: "Сегодня",
    loading: "Загрузка...",
    yourCity: "Ваш город...",
    observations: "Наблюдения",
    observedAt: "Наблюдается в",
    signIn: "Войти",
    yourAccount: "Ваш аккаунт",
    home: "Главная",
    news: "Новости",
    searchMEX: "Поиск MEX",
    weather: "Погода",
    enterCity: "Введите город",
    myLocations: "Мои места",
    recentSearches: "Недавние поиски",
    infoText1:
      "Мы используем ваш почтовый индекс, чтобы предоставить вам актуальную местную информацию по всему MEX.",
    infoText2:
      "Добавьте больше мест, чтобы быть в курсе того, что происходит в местах, которые вам интересны.",
    infoText3: "Вы еще не искали никаких мест.",
    infoText4: "Предыдущие поиски будут отображаться здесь.",
    // Geolocation modal
    allowGeolocation: "Разрешить геолокацию?",
    needLocation:
      "Нам нужно ваше местоположение для отображения данных о погоде",
    decline: "Отклонить",
    accept: "Принять",
    agreeGeo: "Вы согласны с геолокацией?",
    // Weather descriptions and hourly forecast
    weatherDescription: "Погода: {description}",
    precipitation: "Осадки",
    hourlyForecast: "Почасовой прогноз",
    feelsLike: "Ощущается как",
    humidity: "Влажность",
    pressure: "Давление",
    visibility: "Видимость",
    sunrise: "Восход",
    sunset: "Закат",
    wind: "Ветер",
    // Weather conditions
    clear: "Ясно",
    clouds: "Облачно",
    rain: "Дождь",
    snow: "Снег",
    thunderstorm: "Гроза",
    drizzle: "Морось",
    mist: "Туман",
    fog: "Туман",
    // Time periods
    morning: "Утро",
    afternoon: "День",
    evening: "Вечер",
    night: "Ночь",
    // Days of week
    monday: "Понедельник",
    tuesday: "Вторник",
    wednesday: "Среда",
    thursday: "Четверг",
    friday: "Пятница",
    saturday: "Суббота",
    sunday: "Воскресенье",
    // Footer translations
    exploreMex: "Исследуйте MEX",
    copyright:
      "Авторское право © {year} MEX. MEX не несет ответственности за содержание внешних сайтов.",
    readAboutApproach: "Ознакомьтесь с нашим подходом к внешним ссылкам.",
    // About section
    aboutMexWeather: "О погоде MEX",
    faqs: "Вопросы и ответы",
    feeds: "Ленты",
    elsewhere: "В других местах",
    openWeather: "OpenWeather",
    openOffice: "Open Office",
    // Collaborations
    mexWeatherAssociation: "Погода MEX в сотрудничестве с",
    // Observations
    observationStation: "Станция наблюдения:",
    error404: "404!",
    // ads
    eminemAdDesc: "🔥 Новый альбом уже в продаже!",
    aliAdDesc: "🏪 Продадим всё, что угодно без проблем",
    davinciAdDesc: "🎙️ Создавайте свои собственные видео прямо сейчас!",
    nestAdDesc: "🫦 Бэкэнд с классным фреймворком",
    telegramAdDesc: "🚀 Мессенджер, который работает даже на парковке",
  },
};
